### ISSUE TITLE
Search Order should be improved

### ISSUE THREAD

**Issue by Zamiell** [wofsauge/IsaacDocs#126] opened 2021-06-13 16:06 UTC
It's really annoying to start typing "Enti" in the search bar, and have Entity be the last thing on the list behind EntityKnife and such.

Can we make it so that "Entity" is always on top?

GridEntity has the same problem, e.g. if I am typing "GridEn" or something I want it on top before GridEntityDoor and such.

**Comment by wofsauge** [comment] 2021-06-18 17:51
This can be achieved in four ways right now:

1. writing a jquery script that sorts the results when they are displayed. Problem is there, that the search results are loaded in packages of  ~14 entries per load. if you scroll further down it loads more. This behavior is only removeable using strategy 2.
2. Changing the search weights to prioritize the file location name instead of the header title matches. Right now, in the main source code of the theme, the header titles are weighted with a +1000 weight. This value is hard coded and can only be changed by building the theme from scratch and edit the line we need to change in the \assets\javascripts\integrations\search\_\index.ts file . here is the guide for it: https://squidfunk.github.io/mkdocs-material/customization/#theme-development. its alot of work to get it working and also make it work in the current CI, so i will not do it if its not absolutely nessesary.
3. Weighting important files using markdown. This feature is only available in the Sponsorware version of the theme, which costs 10$/month.   see the feature info here: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=sea#boosting-a-page
4. The search query can be edited automatically before it gets commited to the search plugin. Therefore, we can weight certain buzzwords using the LunR search query weights feature. If you put an "exponent" next to a search query word, it gets prioritized higher. Higher exponent = higher priority. Info on that feature is here: https://lunrjs.com/guides/searching.html
example:
![image](https://user-images.githubusercontent.com/245725/122599026-f677ef80-d06d-11eb-97e5-1e5a0b124fa6.png)
As you can see, it gets sorted better, but the bad thing is, that it somehow now matches every single file, even if it does not contain the buzz words. Thats pretty counter productive but can propably be prevented with either post processing jquery scripts that remove files with 0 buzzword matches, or propably with additional search query parameters.

**Comment by Zamiell** [comment] 2021-06-18 18:37
jesus

**Comment by Zamiell** [comment] 2021-06-18 18:38
do you have to use lunr?
what about using this instead? https://github.com/wilhelmer/mkdocs-localsearch

**Comment by wofsauge** [comment] 2021-06-18 18:48
i dont have to use lunr, but thats the default one for all mkdocs applications.

Nonetheless, i tried your mkdocs-localsearch plugin, but it only does change that the support for a static build of the page on a file directory. It does not change the search results as seen here:

![image](https://user-images.githubusercontent.com/245725/122604457-4490f100-d076-11eb-9c5d-43fce0a83657.png)

**Comment by Zamiell** [comment] 2021-06-18 18:58
> the bad thing is, that it somehow now matches every single file

honestly that sounds like either you are somehow specifying the weights in a wrong way, or the plugin itself is bugged

is this the repo for the search? https://github.com/squidfunk/mkdocs-material/issues

**Comment by wofsauge** [comment] 2021-06-18 19:01
Thats the repo for the overall theme which also handles the search requests as mentiones in solution 2.

**Comment by Zamiell** [comment] 2021-06-18 19:10
the [lunr page](https://lunrjs.com/guides/searching.html) doesn't say anything about boosts making a query match every single result, are you sure you are doing everything right?

**Comment by wofsauge** [comment] 2021-06-18 19:15
![image](https://user-images.githubusercontent.com/245725/122606998-2b8a3f00-d07a-11eb-883d-ea7fb10983de.png)

hmm it seems that if i boost the search query and then write a duplicate of the query without boost right behind it, i get a sorted result list... hacky but that could work

**Comment by wofsauge** [comment] 2021-06-18 19:40
Implemented this new method now. My tests seem to result in better sorting of the results. You can try for yourself as well

**Closed by wofsauge** 2021-06-18 19:40 UTC

**Comment by Zamiell** [comment] 2021-06-18 19:45
yeah, works perfectly, nice work
